config/routes.rb
Rails.application.routes.draw do
  get 'maps_testing/index'

  resources :users
  resources :districts
  resources :states
  resources :countries
  resources :products do
    get "delete"
  end
  get '/users/updatestates/:id', to: 'users#updatestates'
  get '/users/updatedistrict/:id', to: 'users#updatedistrict'
  root to: "products#index"
  resources :maps_testing
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :country
  belongs_to :state
end

app/controllers/districts_controller.rb
class DistrictsController < ApplicationController
  before_action :set_district, only: [ :edit, :update, :destroy]

  # GET /districts
  # GET /districts.json
  def index
    @districts = District.all
    @states = State.all
  end

  # GET /districts/1
  # GET /districts/1.json
  def show
    @states = Country.find(params[:id]).states
    # respond_to do |format|
    #   format.js
    # end
  end

  # GET /districts/new
  def new
    @district = District.new
  end

  # GET /districts/1/edit
  def edit
  end

  # POST /districts
  # POST /districts.json
  def create
    @district = District.new(district_params)

    # respond_to do |format|
      if @district.save
        redirect_to districts_path and return
        flash[:notice] = "District created succes"
        # format.html { redirect_to districts_path, notice: 'District was successfully created.' }
        
      # else
      #   format.html { render :new }
      #   format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    # end
  end

  # PATCH/PUT /districts/1
  # PATCH/PUT /districts/1.json
  def update
    respond_to do |format|
      if @district.update(district_params)
        format.html { redirect_to @district, notice: 'District was successfully updated.' }
        format.json { render :show, status: :ok, location: @district }
      else
        format.html { render :edit }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /districts/1
  # DELETE /districts/1.json
  def destroy
    @district.destroy
    respond_to do |format|
      format.html { redirect_to districts_url, notice: 'District was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_district
      @district = District.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def district_params
      params.require(:district).permit(:name, :country_id, :state_id)
    end
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/views/districts/_form.html.erb
<%= form_for district, remote: true do |f| %>
  <% if district.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(district.errors.count, "error") %> prohibited this district from being saved:</h2>

      <ul>
      <% district.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :country_id %>
    <%= f.select :country_id, Country.all.collect{|p| [p.name, p.id]}, include_blank: true , remote: true%>
  </div>

  <div class="field">
    <%= f.label :state_id %>
    <%= f.select :state_id, 'Select Country first' %>
   
  </div>

  <div id="product-modal" class="modal fade">
    He.....
  </div>
 
  <div class="actions">
    <%= f.submit  class: 'submitclasss'%>
  </div>
<% end %>

app/views/districts/_new.html.erb
<option> </option>
<% @states.each do |state| %>
<option value="<%= state.id %>"><%= state.name.titleize %></option>
<% end %>

app/views/districts/edit.html.erb
<h1>Editing District</h1>

<%= render 'form', district: @district %>

<%= link_to 'Show', @district %> |
<%= link_to 'Back', districts_path %>

app/views/districts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Districts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @districts.each do |district| %>
      <tr>
        <td><%= district.name %></td>
        <td><%= district.country %></td>
        <td><%= district.state %></td>
        <td><%= link_to 'Show', district %></td>
        <td><%= link_to 'Edit', edit_district_path(district) %></td>
        <td><%= link_to 'Destroy', district, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New District', new_district_path %>

app/views/districts/new.html.erb
<h1>New District</h1>

<%= render 'form', district: @district %>

<%= link_to 'Back', districts_path %>

app/views/districts/show.js.erb
$("#district_state_id").empty()
  .append("<%= escape_javascript(render 'new') %>");